language: java

jdk:
  - oraclejdk8

after_success:
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux

sudo: false # faster builds

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle
