language: java

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux

sudo: false # faster builds

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle
