language: java

jdk:
  - oraclejdk8

os:
  - linux

dependencies:
  post:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

sudo: false # faster builds

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

after_success:
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - bash <(curl -s https://codecov.io/bash)

test:
  pre:
    - ./cc-test-reporter before-build
  post:
    - ./cc-test-reporter after-build --exit-code $EXIT_CODE
