language: java

jdk:
  - oraclejdk8

os:
  - linux

sudo: false

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

after_success:
  - cat codecov.yml | curl --data-binary @- https://codecov.io/validate
  - bash <(curl -s https://codecov.io/bash)
